replicaCount: 2

image:
  repository: kksudo/helm-demo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "production"
  
fullnameOverride: "it-onedevopschampion"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: production.lclhost.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - production.lclhost.xyz
      secretName: production-lclhost-xyz

autoscaling:
  enabled: false
