replicaCount: 1

image:
  repository: kksudo/helm-demo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "develop"
  
fullnameOverride: "develop-it-onedevopschampion"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: $LOCAL_ENV.lclhost.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - $LOCAL_ENV.lclhost.xyz
      secretName: $LOCAL_ENV-lclhost-xyz

autoscaling:
  enabled: false
