name: Development workflow

on:
  push:
    branches:
      - develop
env:
  LOCAL_ENV: development
  
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: kksudo
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kksudo/helm-demo:develop,kksudo/helm-demo:${{ env.LOCAL_ENV }}-${{ github.sha }}
          
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: helm lint
        run: |
          helm lint helm/helm-demo -f helm/environments/${{ env.LOCAL_ENV }}/values.yaml
        
  deploy:
    runs-on: ubuntu-latest
    needs: [helm-check, image-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy app to the ${{ env.LOCAL_ENV }} namespace
        uses: okar1/yc-helm@master
        with:
          SA_KEY: ${{ secrets.YC_SA_KEY }}
          K8S_CLUSTER_ID: cat18t221ikr50a0hb4i
          HELM_ARGS: -n ${{ env.LOCAL_ENV }} install app ./helm/helm-demo  -f helm/environments/${{ env.LOCAL_ENV }}/values.yaml
