name: Development workflow

on:
  push:
    branches:
      - develop
env:
  LOCAL_ENV: development
  
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: kksudo
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kksudo/helm-demo:develop,kksudo/helm-demo:$LOCAL_ENV-${{ github.sha }}
          
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: helm lint
        run: |
          helm lint helm/helm-demo -f helm/environments/$LOCAL_ENV/values.yaml
        
      
